server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 521liuyan
#设置控制台打印SQL
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired


missyou:
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://localhost:8081
    pay-callback-path: /v1/payment/wx/notify
